### ISSUE TITLE
typings for typescript

### ISSUE THREAD

**Issue by FDiskas** [clarketm/saga-monitor#5] opened 2020-02-17 13:52 UTC
Please add a support for typescript users :)
```
Could not find a declaration file for module '@clarketm/saga-monitor'. '***@clarketm/saga-monitor/dist/saga-monitor.js' implicitly has an 'any' type.
  Try `npm install @types/clarketm__saga-monitor` if it exists or add a new declaration (.d.ts) file containing `declare module '@clarketm/saga-monitor';`
```
and add them directly to package

thanks

**Comment by clarketm** [comment] 2020-02-19 06:35
Duplicate of #2

**Closed as completed by clarketm** 2020-02-19 06:35 UTC
